;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_putch
	.export		_main

; ---------------------------------------------------------------
; void __near__ __fastcall__ putch (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_putch: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	ora     #$80
	sta     $D012
L0025:	lda     $D012
	and     #$80
	bne     L0025
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$48
	jsr     _putch
	lda     #$65
	jsr     _putch
	lda     #$6C
	jsr     _putch
	lda     #$6C
	jsr     _putch
	lda     #$6F
	jsr     _putch
	lda     #$2C
	jsr     _putch
	lda     #$20
	jsr     _putch
	lda     #$57
	jsr     _putch
	lda     #$6F
	jsr     _putch
	lda     #$72
	jsr     _putch
	lda     #$6C
	jsr     _putch
	lda     #$64
	jsr     _putch
	lda     #$21
	jmp     _putch

.endproc

